### ISSUE TITLE
2.0 - replacetool is iffy on rightclick

### ISSUE THREAD

**Issue by Zarius** [Zarius/Bukkit-OtherBlocks#103]
This config gets a bit buggy:

```
  COW:
    - action: RIGHT_CLICK
      tool: BUCKET
      replacetool: WATER_BUCKET
      message: Water from a cow!
```

Often the water will spill out to the ground (seems the rightclick event occurs after the bucket has been replaced) and if we add an event cancellation on the second line of onPlayerInteract we still sometimes get buckets of milk?
