### ISSUE TITLE
2.0 - issues with Entity drops

### ISSUE THREAD

**Issue by Zarius** [Zarius/Bukkit-OtherBlocks#106]
```
 ZOMBIE:
    - tool: ANY_SWORD   # bug: player attacks on creatures are recorded as damage_entity_attack and don't match the sword
      drop: CHAINMAIL_HELMET
      chance: 100
      message: ["A little dusty, but this chainmail helmet might look good on you."]
    - tool: ANY  
      drop: MONEY  # bug: entity attacks - recipient is null
      quantity: 150
      chance: 100     
```
