### ISSUE TITLE
New drop configuration allowing ordered events?

### ISSUE THREAD

**Issue by Zarius** [Zarius/Bukkit-OtherBlocks#115]
Just playing with ideas but a different config (using ordered lists) for the drops could be:

```
  GRASS:
    - drop:
        - tool: ANY
        - drop: APPLE
        - message: There's an apple!
        - delay: 20
        - event: LIGHTNING
        - message: And here's lightning!
        - delay: 60
        - command: [/time night]
        - message: And now it's night!
```
