### ISSUE TITLE
XP Drops Overriding Loot Drops

### ISSUE THREAD

**Issue by Steelsouls** [Zarius/Bukkit-OtherBlocks#125]
I'm having a problem with my drops from Coal Ore, Iron Ore, Redstone Ore (incl. glowing), and Diamond Ore. They worked fine until recently and I'm not sure what changed.  All I have them drop extra is XP.  I have tried in the config to do every combination of overrides true/false (I'd like them all to be false and just do "extra" drops). None of the config overrides seem to have an effect.  If I set the percent drop chance for XP to be low, then the items drop when the XP does not trigger.  As soon as OtherDrops gets triggered for the drop no items are made.  Here is the part of the config for these drops.

Version: This happens on both 2.8 beta1 and 2.8 beta2.

aliases:
    - &pickaxeNoSilkTouch [ANY_PICKAXE, -DIAMOND_PICKAXE@!SILK_TOUCH, -GOLD_PICKAXE@!SILK_TOUCH, -IRON_PICKAXE@!SILK_TOUCH, -STONE_PICKAXE@!SILK_TOUCH, -WOODEN_PICKAXE@!SILK_TOUCH]

```
COAL_ORE:
    - tool: *pickaxeNoSilkTouch
      drop: XP/17
    - tool: *pickaxeNoSilkTouch
      drop: DIAMOND/1%/1-5
      message: ["Wow! This coal became a diamond!"]
LAPIS_ORE:
    - tool: *pickaxeNoSilkTouch
      drop: XP/32
DIAMOND_ORE:
    - tool: *pickaxeNoSilkTouch
      drop: XP/48
REDSTONE_ORE:
    - tool: *pickaxeNoSilkTouch
      drop: XP/24
GLOWING_REDSTONE_ORE:
    - tool: *pickaxeNoSilkTouch
      drop: XP/24
```
