### ISSUE TITLE
Bug Report - Death by Anvil error

### ISSUE THREAD

**Issue by Steelsouls** [Zarius/Bukkit-OtherBlocks#129]
Error log: http://pastebin.com/v0j9eiVR

Drop parameters that caused the error

```
PLAYER:
    - tool: ANVIL
      drop: GOLD_NUGGET/7
      message.server: ["Splat!!!"]
```

This is just a fun little drop that is exceedingly rare. I thought I'd test it this morning and obviously you see what happened. It's not a pressing matter, just wanted to report it so you are aware of the issue.  Thanks!

Edit: Also tried tool: FALLING_BLOCK
also tried tool: ANVIL with action: HIT for easier testing
- Both of these further tests also resulted in errors.
