### ISSUE TITLE
Silverfish spawn from all cobblestone blocks when broken!

### ISSUE THREAD

**Issue by Zarius** [Zarius/Bukkit-OtherBlocks#130]
Hi Zarius. This is Chuck67322's cousin, and I'm using your plugin for disabling slimes in swamp biomes (thanks!). I made a crazy config and put it on another server, but for some reason, every time someone breaks cobblestone, a silverfish spawns. It's not specified anywhere in my config. This is all I have besides the comments and such that come with the file. Everything is default except for this in the drops YML:

```
DIAMOND_ORE:
    - drop: ENDERDRAGON

    - drop: WITHER

COW:
    - drop: ZOMBIE

ZOMBIE:
    - drop: ZOMBIE

```
