### ISSUE TITLE
Issue with snow golems and mobspawn action

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#141]
This causes the snowman@20h drop to occur but the two snow blocks and the pumpkin used to create the snowman don't disappear(thus allowing the infinite creation of snowmen if you pick them back up and keep placing them.) I'm guessing the event is being canceled by otherdrops.

```
SNOWMAN:
    - action: MOBSPAWN
      drop: SNOWMAN@20h
      spawnedby: BUILD_SNOWMAN
```
