### ISSUE TITLE
Call spawnedby: parameter on action: MOBSPAWN

### ISSUE THREAD

**Issue by Steelsouls** [Zarius/Bukkit-OtherBlocks#142]
Or simply have action: MOBSPAWN affect mobs spawned by OtherDrops.

Is this supposed to work or does the mob have to actually spawn for spawnedby: to recognize it?

Following entries are for gluton (hangs out in IRC). He wants to spawn groups of zombies (works), but some of the spawns to have equipment (works only on vanilla zombie spawns)

When calling action: MOBSPAWN it only works on mobs spawned normally by the server

```
    ZOMBIE:
      - action: MOBSPAWN
        drop: ["zombie@eq:hands:STONE_SWORD!!eq:chest:LEATHER_CHESTPLATE", "ZOMBIE@60h!!eq:head:LEATHER_HELMET/50%"]
      - action: MOBSPAWN
        drop: {"ZOMBIE/2/30%", "ZOMBIE/3/15%", "ZOMBIE/4/5%", "ZOMBIE/5/1%"}
```

The intended setup could work by doing complicated drop groups with different equipment setups, I just think it would be much simpler to catch all mob spawns and say every zombie has x% to have this equipment.
