### ISSUE TITLE
health and hunger parameters (health.victim, health.server, etc.)

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#143]
Requesting that health and hunger parameters that work similar(if not identical to) to the damage, message and potioneffect parameters. Optionally they could be used to reduce hunger(not needed for health because of damage parameter.) and optionally add saturation options for hunger.

```
ANY_BLOCK:
    - action: RIGHT_CLICK
      tool: COOKED_FISH@10
      lorename: Cooked Tuna
      hunger.attacker: 6
      consumetool: 1
PLAYER:
    - action: RIGHT_CLICK
      tool: POTION@8197
      health.victim: 6
      consumetool: 1
      message.victim: "%p used a health potion on you!"
```
