### ISSUE TITLE
Tools aren't checked for multiple enchantments

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#144]
Tools that contain multiple enchantments are only checking if the first enchantment is on the tool.

This example allows the drop to occur if just the thorns enchantment is present. (it doesn't check to see if the flame enchantment is there.)

```
IRON_ORE:
    - tool: DIAMOND_PICKAXE@!THORNS#3!ARROW_FIRE#1
      drop: IRON_INGOT
      message: "&aYour pickaxe heats up the ore."
```
