### ISSUE TITLE
Damage parameter on snowballs cause mobs to ignore snowmen

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#145]
While trying to make snowmen more useful I found that putting a damage parameter on snowballs cause snowmen to be ignored by mobs they attack, kind of makes them very overpowered killing machines.

```
ANY_CREATURE:
    - action: HIT
      tool: PROJECTILE_SNOW_BALL
      damage.victim: 3
      potioneffect.victim: SLOW@60@2
```
