### ISSUE TITLE
loc-offset to effect replacementblock

### ISSUE THREAD

**Issue by Zarius** [Zarius/Bukkit-OtherBlocks#161]
Posted on BukkitDev tickets by Tajin

I think it might be useful if the offset-settings would also have an effect on the coordinates where a block is beeing replaced via "replacementblock"

This would allow to change the surrounding blocks.

Here's a random example:

```
DIAMOND_BLOCK:
  - tool: AIR
    action: LEFT_CLICK
    dropgroup: cage
    drops:
      - loc-offset: 0/1/0
        replacementblock: IRON_FENCE
      - loc-offset: 0/0/1
        replacementblock: IRON_FENCE
      - loc-offset: -1/0/0
        replacementblock: IRON_FENCE
      - loc-offset: 0/0/-1
        replacementblock: IRON_FENCE
      - loc-offset: 1/0/0
        replacementblock: IRON_FENCE
      - loc-offset: 1/1/0
        replacementblock: IRON_FENCE  
      - loc-offset: -1/1/0
        replacementblock: IRON_FENCE
      - loc-offset: 0/1/-1
        replacementblock: IRON_FENCE
      - loc-offset: 0/1/1
        replacementblock: IRON_FENCE
```

Punching the diamond_block would spawn a cage around it.
