### ISSUE TITLE
Creature Giant

### ISSUE THREAD

**Issue by Qcbob** [Zarius/Bukkit-OtherBlocks#173]
I am testing something which allow me to spawn Giant on top of mountain in an Extreme_Hills Biome. It work great, the issue is about giving custom drop to Giant, maybe I do something wrong or there is a bug somewhere. I have see the Creature List of OtherDrops page and Bukkit Entity name and use Giant. 
# This is the code to spawn Giant. The tower is actually highest place around in the biome, so only Giant can spawn there

```
 CREATURE_HOSTILE:
  - action: MOBSPAWN
    drop: GIANT
    height: ">170"
    lightlevel: 4
    message.server: "&cA player&f found a &7&LGiant &f on top of the tower!"
    chance: 100%
```

 #When I add this code, nothing work at all, it's like it does'nt recognize "GIANT" and screw the rest of the code:
    GIANT:
      - drop: EMERALD/25-50/35%
      - command: "/*rpgitem gaxe give %p"
        message: "&c%p&f found an &9&LAxe of the Sky Son &f!"
        chance: 5% 

I don't think that's because of the command, which is also use with other Mobs and work perfectly. Everything work on the Online Yaml Parser. Thanks for your support!
