### ISSUE TITLE
exclusive parameter not working, sometimes many drops firing...

### ISSUE THREAD

**Issue by israelcurtis** [Zarius/Bukkit-OtherBlocks#187]
I've been using "flag:unique" as the "exclusive" parameter has been random and useless. I would like to be able to use "exclusive", however, when dealing with groups of related drops where I only want one to fire. I also don't want to use "unique" because it prevents other action events from firing that match the same conditions.

In this example, I have a special shovel that deals three possible levels of damage (based on the enderdragon example (http://dev.bukkit.org/server-mods/otherdrops/pages/basic-examples/)

Even though all action nodes are part of the same exclusive group, sometimes I'll see a dozen events fire, with my debugging messages "low,low,low,medium,high,high,villager killed, villager killed, villager kililed" -- just from _one hit_ with the shovel. Doesn't happen with "flag:unique"..

```
VILLAGER:
  - action: HIT
    tool: ironshovel@!~the Smacker
    damage.victim: 3
    sound: HURT
    chance: 50%
    exclusive: 1
    message: "low"
  - action: HIT
    tool: ironshovel@!~the Smacker
    damage.victim: 9
    sound: HURT
    chance: 25%
    exclusive: 1
    message: "medium"
  - action: HIT
    tool: ironshovel@!~the Smacker
    damage.victim: 50
    message: "§8SMACK!"
    effect: ZOMBIE_CHEW_IRON_DOOR
    chance: 25%
    damagetool: 30
    exclusive: 1
    message: "high"
```
