### ISSUE TITLE
sound parameters don't work in shorthand bracket groups

### ISSUE THREAD

**Issue by israelcurtis** [Zarius/Bukkit-OtherBlocks#190]
wanting to have a collection of possible sounds that play, but obviously only one at a time (if i used [], they all play at once). tried the {} syntax, but it fails to play anything:

```
  action: HIT
  tool: ANY_SWORD
  sound: {HURT,HURT/0.75p,HURT/0.85p,HURT/1.25p,HURT/1.5p}
```

which means i have to use a giant dropgroup to accomplish:

```
 dropgroup: bloodshed
  action: HIT
  tool: ANY_SWORD
  drops:
    - sound: HURT
      chance: 20%
    - sound: HURT/0.75p
      chance: 20%
    - sound: HURT/0.85p
      chance: 20%
    - sound: HURT/1.25p
      chance: 20%
    - sound: HURT/1.5p
      chance: 20%
```
