### ISSUE TITLE
Different drops for clicking ANVIL@0, ANVIL@1, and ANVIL@2

### ISSUE THREAD

**Issue by sehrgut** [Zarius/Bukkit-OtherBlocks#200]
I'm trying to implement anvil repair with the following drop:

```
ANVIL:
  - action: LEFTCLICK
    tool: IRON_INGOT
    consumetool: 1
    replacementblock: ANVIL@0
    event: LIGHTNING@HARMLESS
    message: Your anvil has been repaired.
```

What I'd like to do is have separate rules with separate costs and effects for each damage level, so that repairing ANVIL@0 would be a no-op, repairing ANVIL@1 would yield ANVIL@0, and repairing ANVIL@2 would yield ANVIL@1. 4 could then yield 3, and 5 could yield 4, preserving orientation.

Would this be a feature you could add?
