### ISSUE TITLE
Color and lore support for written books

### ISSUE THREAD

**Issue by VoxPopuliZombiemold** [Zarius/Bukkit-OtherBlocks#201]
Written books don't seem to support colors in their name, or allow for lore of any kind.

A drop like:

```
Monster_Eggs:
  - drop: writtenbook@~&4Deep Discoveries:&6Archeology Journal 05:author=DoosyDittle:page=Day 32 - It's been weeks into our expedition, but all my men have been able to excavate has been a few caveman skeletons and old pottery. I am thinking that we need to go deeper underground, now if only I can get us the grant money.:page=Day 48 - Finally convinced my sponsors to dish out the cash, now we can finally excavate at the levels we need, lets hope this pays off.:page=Day 49 - Eureka. We found a pefectly intact dragon skeleton, and so close to bedrock. I estimate roughly 6 blocks above completely dense bedrock. Now if only we had found this sooner before the pockets of our sponsor dried out.
    chance: 100%
    flags: UNIQUE
```

Doesn't work at all it would seem. Something like this:

```
Monster_Eggs:
  - drop: writtenbook@author=DoosyDittle~&5Deep Discoveries:&6Archeology Journal 05:page=Day 32 - It's been weeks into our expedition, but all my men have been able to excavate has been a few caveman skeletons and old pottery. I am thinking that we need to go deeper underground, now if only I can get us the grant money.:page=Day 48 - Finally convinced my sponsors to dish out the cash, now we can finally excavate at the levels we need, lets hope this pays off.:page=Day 49 - Eureka. We found a pefectly intact dragon skeleton, and so close to bedrock. I estimate roughly 6 blocks above completely dense bedrock. Now if only we had found this sooner before the pockets of our sponsor dried out.
    chance: 100%
    flags: UNIQUE
```

Doesn't work either. and lastly, something like this: 

```
Monster_Eggs:
  - drop: writtenbook@author=DoosyDittle:title=&5Deep Discoveries:&6Archeology Journal 05:page=Day 32 - It's been weeks into our expedition, but all my men have been able to excavate has been a few caveman skeletons and old pottery. I am thinking that we need to go deeper underground, now if only I can get us the grant money.:page=Day 48 - Finally convinced my sponsors to dish out the cash, now we can finally excavate at the levels we need, lets hope this pays off.:page=Day 49 - Eureka. We found a pefectly intact dragon skeleton, and so close to bedrock. I estimate roughly 6 blocks above completely dense bedrock. Now if only we had found this sooner before the pockets of our sponsor dried out.
    chance: 100%
    flags: UNIQUE
```

Doesn't work either.
