### ISSUE TITLE
"health" condition

### ISSUE THREAD

**Issue by sehrgut** [Zarius/Bukkit-OtherBlocks#203]
I'd like to encourage not-quite-to-the-death PVP on my server by allowing players to capture each other's heads. Essentials /give allows me to award the trophy, but I'd love to have a "health" condition (or better yet, separate player-health and victim-health conditions) so that I can award the trophy on wearing someone down to a particular number of half-hearts.

```
otherdrops:
  PLAYER:
    - action: HIT
      command: "/$give %p head:3 player:%v"
      message.server: %p has acquired %v's head
      victim-health: 4
```
