### ISSUE TITLE
Fortune (Loot_Bonus_Blocks) Problem.

### ISSUE THREAD

**Issue by iForFi** [Zarius/Bukkit-OtherBlocks#205]
Weel i need a help with this thing
My Drop:

```
STONE:
    - drop: IRON_ORE
      tool: [ANY_PICKAXE]
      chance: 2.2
      message: "Gratulacje. Znalazles &7Iron Ore&f."
    - drop: IRON_ORE
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#1
      chance: 2.4
      message: "Gratulacje. Znalazles &7Iron Ore1&f."
    - drop: IRON_ORE
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#2
      chance: 2.6
      message: "Gratulacje. Znalazles &7Iron Ore2&f."
    - drop: IRON_ORE
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#3
      chance: 2.8
      message: "Gratulacje. Znalazles &7Iron Ore3&f."
    - drop: GOLD_ORE
      tool: [ANY_PICKAXE]
      chance: 0.6
      message: "Gratulacje. Znalazles &eGold Ore&f."
    - drop: GOLD_ORE
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#1
      chance: 0.75
      message: "Gratulacje. Znalazles &eGold Ore1&f."
    - drop: GOLD_ORE
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#2
      chance: 0.9
      message: "Gratulacje. Znalazles &eGold Ore2&f."
    - drop: GOLD_ORE
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#3
      chance: 1.05
      message: "Gratulacje. Znalazles &eGold Ore3&f."
    - drop: EMERALD
      tool: [ANY_PICKAXE]
      chance: 0.5
      message: "Gratulacje. Znalazles &aEmerald&f."
    - drop: EMERALD
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#1
      chance: 0.6
      message: "Gratulacje. Znalazles &aEmerald1&f."
    - drop: EMERALD
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#2
      chance: 0.7
      message: "Gratulacje. Znalazles &aEmerald2&f."
    - drop: EMERALD
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#3
      chance: 0.8
      message: "Gratulacje. Znalazles &aEmerald3&f."
    - drop: DIAMOND
      tool: [ANY_PICKAXE]
      chance: 0.4
      message: "Gratulacje. Znalazles &bDiament&f."
    - drop: DIAMOND
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#1
      chance: 0.45
      message: "Gratulacje. Znalazles &bDiament1&f."
    - drop: DIAMOND
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#2
      chance: 0.5
      message: "Gratulacje. Znalazles &bDiament2&f."
    - drop: DIAMOND
      tool: ANY_PICKAXE@!LOOT_BONUS_BLOCKS#3
      chance: 0.55
      message: "Gratulacje. Znalazles &bDiament3&f."
```

And when i use a normal pickaxe without any enchant it still drops a loot_bonus_blocks setup. I see because i put in the msg 1, 2, 3 as you may see. Anyone help me with a fix? Is this even possible in this plugin? So that fortune will work. I'll thanks SOOOOO much.
