### ISSUE TITLE
[Feature Request] face parameter for action: BREAK

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#213]
I am needing the face parameter to be adapted to work with action: BREAK

My reason is that I am needing to cancel a block from being broken from the bottom face, but allow it from all other faces, as in the following code:

```
otherdrops:
    MOB_SPAWNER:
      - tool: ANY
        action: BREAK
        face: DOWN
        replacementblock: MOB_SPAWNER@this
```

or more preferably (if it works):

```
otherdrops:
    MOB_SPAWNER:
      - tool: ANY
        action: BREAK
        face: DOWN
        drop: DENY
```
