### ISSUE TITLE
[Feature Request] event: NOPHYSICS and event: NOFLOW

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#214]
I was looking through the documentation and after testing a feature that should be in the build, `event: NOPHYSICS`, I noticed that the feature was not actually added. In addition to having that added, I would also like to request an `event: NOFLOW`. The reason I am needing an `event: NOFLOW` is so that I can successfully create a way to prevent afk cobble farming, using the following code:

```
otherdrops:
    COBBLESTONE:
      - tool: ANY
        drop: DEFAULT
        chance: 100%
      - tool: ANY
        event: NOFLOW
        chance: 1.0%
```
