### ISSUE TITLE
[Bug] loc-randomise broken [Feature Request] dropspread: true alongside loc-randomise

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#215]
While attempting to make a snow block place each snowball in a different location, I ran into an issue where`loc-randomise` does not work at all. In addition to that, I was also curious if using `dropspread: TRUE` alongside `loc-randomise: 3/3/3` will either place each of the 4 snowballs in a random location, or just spread out the 4 snowballs in the same random location. Here is the code I am attempting to work with:

```
otherdrops:
    SNOW_BLOCK:
      - tool: ANY
        drop: snowball/4
        dropspread: true
        loc-randomise: 3/3/3
```
