### ISSUE TITLE
[Feature Request] Cooldowns stored between restarts and a variable for messages

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#218]
My first feature request is for the cooldowns (in the current dev build) to be stored between server restarts. Pretty straightforward, no need for more explanation.

My second feature request is to add a way to display the remaining time until the cooldown expires using a message. This could possibly be done in the following config:

```
otherdrops:
    MOB_SPAWNER:
        - tool: ANY_OBJECT
          drop: DENY
          flag: UNIQUE
          cooldown: mobspawner.$p@43200
          message@cooldown: '§6You must wait %c-mobspawner.$p seconds before you are able to break another spawner.'
```

I highly recommend making your own option as mine is pretty messy...
