### ISSUE TITLE
[Bug] Drops for named mobs broken in 2.8b.526

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#222]
Upon upgrading to this version my configuration for named mobs stopped working completely. Below is an example showing one of my named mobs drops and its normal counterpart. The named mob doesn't drop any of the items in its drop list but still drops the normal mobs drops(even though it has drop: nothing set) This config worked fine before.

```
CHICKEN:
    - action: MOBSPAWN
      drop: CHICKEN~Turkey
      chance: 10
    - tool: PLAYER
      drop: SEEDS/1-3
    - tool: PLAYER
      drop: WHEAT/1-2/25%
CHICKEN~Turkey:
    - tool: PLAYER
      drop: RAW_CHICKEN@1
      quantity: 1-2
    - drop: NOTHING
    - tool: PLAYER
      drop: FEATHER@1
      quantity: 1-4
```
