### ISSUE TITLE
[Feature Request] loc-randomize, dropspread: true combination

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#229]
Currently when `loc-randomize: 3/3/3` is set and `dropspread:true` is set, all drops will be dropped in the same random location individually (and then combined by minecraft). What I think should happen is that each drop should be placed in it's own random location.

I would also like to see (if it is not added already) support for radius ranges for loc-randomize. For example `loc-randomize: 2-3/0/2-3` would drop the item between 2 and 3 meters radius of the block, but no more than 3 and no less than 2.

 Allow me to explain with a few examples:

---

```
otherdrops:
    MOB_SPAWNER:
      - tool: PLAYER
        drop: [zombie/1-3, pigzombie/1-3, blaze/1, witch/1, contents/1-3, xp/100]
        dropspread: true
        loc-randomize: 3/1/3
      - tool: PLAYER
        drop: [MONEY/100, emerald/2-4]
        dropspread: true
```

What this will do is place the 1-3 zombies in one random location, place the 1-3 pigzombies in a seperate random location, place the witch in a seperate random location, the type of mob that the spawner would make be dropped in a seperate random location, and the xp be divided up (being dropspread is true) but still all placed in the same random location.

What it will do with the second part is drop the money in the location of the spawner along with the 2-4 emeralds, which are not stacked (because dropspread is true).

---

Now, say for example you were wanting the 1-3 zombies to be placed in their own separate random location, along with dividing the xp into groups of 25 and placing them into random locations on the outskirts of the mobs. You would do this like so:

```
otherdrops:
    MOB_SPAWNER:
      - tool: PLAYER
        drop: [ZOMBIE/100%, ZOMBIE/50%, ZOMBIE/50%, pigzombie/1-3, blaze/1, witch/1, contents/1-3]
        dropspread: true
        loc-randomize: 3/1/3
      - tool: PLAYER
        drop: [xp/25, xp/25, xp/25, xp/25]
        dropspread: true
        loc-randomize: 4-5/1/4-5
      - tool: PLAYER
        drop: [MONEY/100, emerald/2-4]
        dropspread: true
```

As you can see, we divided each zombie into its own drop and gave the last two a 50% chance, that way it is still 1-3, however, each zombie will now be placed in it's own random location.

As you acn see with the xp, we have placed each xp into a group of 25 and it will also each be placed in its own random location. As you can also see, we have also given each XP it's own random location 4-5 meters from the spawner.

---

The only possible issue I can see this causing is if a player didn't want the drops to spread but did want them to each be placed in a random location, which is why you could `loc-randomize: 3/1/3@perdrop`.
