### ISSUE TITLE
[Feature Request] Addition of replacementmob

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#239]
I am wanting to do the following, however, when I do it, it replaces the fence the chicken was standing on with air. I figured a simple solution to this would be to replace the entity instead of the block.

**Before:**

```
otherdrops: 
    CHICKEN:
      - tool: MONSTER_EGG@0
        action: RIGHT_CLICK
        consumetool: 1
        replacementblock: air
        flag: UNIQUE
        drop: MONSTER_EGG@THIS
        message: ["&bAll right! &bYou caught &c%v&b!"]
      - tool: [ANY_TOOL, ANY_OBJECT]
        drop: default
```

**After:**

```
otherdrops: 
    CHICKEN:
      - tool: MONSTER_EGG@0
        action: RIGHT_CLICK
        consumetool: 1
        replacementmob: air
        flag: UNIQUE
        drop: MONSTER_EGG@THIS
        message: ["&bAll right! &bYou caught &c%v&b!"]
      - tool: [ANY_TOOL, ANY_OBJECT]
        drop: default
```
