### ISSUE TITLE
[Bug] Minor bug using LEAVES@THIS as a drop

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#243]
This set-up produces leaves with alternate data values that don't stack with normal leaves(of any kind) They all have the correct textures but are all called Oak Leaves. (data 4-7)

```
LEAVES:
    - tool: SHEARS
      drop: NOTHING
    - tool: SHEARS
      drop: LEAVES@THIS
    - tool: SHEARS
      drop: STICK@1~&aTree Branch;&bA tree branch cut from a large tree.;&bCan be sold or used in crafting./1-2
```
