### ISSUE TITLE
Build #86 broke this set up(not sure what part is broken)

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#245]
This is my test configuration for testing my bandit mobs and upon updating from build 82 to build 86 it stopped working(not sure about builds in-between)
When you right click sand as an OP(no one actually has the admin permission used here) its supposed to spawn a few renamed zombies that wear various armor which no longer works in this build.

```
SAND:
    - dropgroup: bandits1
      trigger: RIGHT_CLICK
      permission: admin
      drops: 
          - drop: ZOMBIE@eq:head:SKULL_ITEM@Steve%0!!eq:hands:IRON_SWORD%0!!eq:feet:LEATHER_BOOTS%0!!eq:chest:IRON_CHESTPLATE%0!!eq:legs:IRON_LEGGINGS%0!!50h~&dBandit Warrior/1
            potioneffect.drop: SPEED@6000@2
          - drop: SKELETON@eq:head:SKULL_ITEM@Steve%0!!eq:hands:BOW%0!!eq:feet:LEATHER_BOOTS%0!!eq:chest:LEATHER_CHESTPLATE%0!!eq:legs:LEATHER_LEGGINGS%0!!30h~&dBandit Archer/0-2
            potioneffect.drop: SPEED@6000@2
          - drop: ZOMBIE@eq:head:SKULL_ITEM@Steve%0!!eq:hands:GOLD_SWORD%0!!eq:feet:LEATHER_BOOTS%0!!eq:chest:GOLD_CHESTPLATE%0!!eq:legs:GOLD_LEGGINGS%0!!70h~&dBandit Leader/1
            chance: 20
            potioneffect.drop: SPEED@6000@2
          - drop: ZOMBIE@eq:head:SKULL_ITEM@Herobrine%0!!eq:hands:DIAMOND_SWORD%0!!eq:feet:LEATHER_BOOTS%0!!eq:chest:DIAMOND_CHESTPLATE%0!!eq:legs:DIAMOND_LEGGINGS%0!!100h~&dBandit Overlord/1
            chance: 1
            potioneffect.drop: [SPEED@6000@2, INCREASE_DAMAGE@6000@1]
```
