### ISSUE TITLE
Confliction between two files, extremely irrelevant to each other

### ISSUE THREAD

**Issue by clucky** [Zarius/Bukkit-OtherBlocks#247]
I am having a confliction between two drop files. The first one is completely disabled by the second. I am using Otherdrops Developmental Build 89.

```
otherdrops:
    BAT:
      - tool: ANY
        drop: xp/10
        chance: 100%
        message.attacker: '[DEBUG] The Bat drops some XP'
      - tool: ANY
        drop: {APPLE/1/25%, MELON/1-2/25%, INK_SAC@15/1-2/25%}
        message.attacker: '[DEBUG] The Bat drops an item.'
```

```
alisas:
        - &evaporate [DESERT, DESERT_HILLS, HELL]
        - &freeze [FROZEN_OCEAN, FROZEN_RIVER, ICE_MOUNTAINS, ICE_PLAINS, TAIGA, TAIGA_HILLS]
        - &silktouch [WOOD_PICKAXE@!SILK_TOUCH, STONE_PICKAXE@!SILK_TOUCH, IRON_PICKAXE@!SILK_TOUCH, DIAMOND_PICKAXE@!SILK_TOUCH, GOLD_PICKAXE@!SILK_TOUCH, IRON_SHOVEL@!SILK_TOUCH, WOOD_SHOVEL@!SILK_TOUCH, STONE_SHOVEL@!SILK_TOUCH, GOLD_SHOVEL@!SILK_TOUCH, DIAMOND_SHOVEL@!SILK_TOUCH, WOOD_AXE@!SILK_TOUCH, STONE_AXE@!SILK_TOUCH, IRON_AXE@!SILK_TOUCH, GOLD_AXE@!SILK_TOUCH, DIAMOND_AXE@!SILK_TOUCH, WOOD_HOE@!SILK_TOUCH, STONE_HOE@!SILK_TOUCH, IRON_HOE@!SILK_TOUCH, GOLD_HOE@!SILK_TOUCH, DIAMOND_HOE@!SILK_TOUCH]

otherdrops:
    ICE:
#Has a percentage chance to evaporate in &evaporate
        - tool: ANY
          drop: NOTHING
          chance: 10 #change this value to change the chance of ice being replaced by water when broken
          biome: *evaporate
          flag: unique
          replacementblock: WATER
        - tool: ANY
          drop: NOTHING
          biome: *evaporate
          flag: unique
          replacementblock: NOTHING

#Silk touch only drops ice + water in &freeze
        - tool: *silktouch
          drop: ICE
          biome: *freeze
          flag: UNIQUE
          replacementblock: WATER

#General
        - tool: ANY
          drop: NOTHING
          replacementblock: water
        - tool: *silktouch
          drop: ICE
          replacementblock: NOTHING
```
