### ISSUE TITLE
[Bug] Fishing events seem bugged in latest versions

### ISSUE THREAD

**Issue by charlie1990** [Zarius/Bukkit-OtherBlocks#249]
I'm not sure which version this started happening in but this no longer produces any of the fish I have it set to, it only gives default fish(349:0)

Using OtherDrops Build 90

```
PLAYER:
    - trigger: FISH_CAUGHT
      tool: FISHING_ROD
      lorename: "&dBroken Rod"
      drop: {RAW_FISH@5/50%, RAW_FISH@6/25%, RAW_FISH@7/15%, RAW_FISH@8/7%, RAW_FISH@9/3%}
      damagetool: 1
      chance: 100
      permission: fishing.sardine
      flag: UNIQUE
      commands: /!*addxp %p fishing 800
```
