### ISSUE TITLE
Infinite explosion loop

### ISSUE THREAD

**Issue by Zarius** [Zarius/Bukkit-OtherBlocks#259]
Tested in OtherDrops 2.8b.557

```
  ANY_BLOCK:
    - action: HIT
      tool: ANY
      message.server: "bang!"
      event: EXPLOSION
```

Marking as minor as unlikely someone will try that paritcular config (hasn't been reported yet).
