### ISSUE TITLE
Formatting stops lorename check from working

### ISSUE THREAD

**Issue by Blacklands** [Zarius/Bukkit-OtherBlocks#271]
I'm working on a smithing system, and while doing so, I noticed that the lorename check doesn't seem to work anymore as soon as you put ANY formatting codes in it.

I've had this set up for Anvils:

---

```
anvil:
- permission: smithsforgingdrops
  trigger: left_click
  tool: iron_sword@251
  lorename: "Raw Iron Sword (Hot)"
  damagetool: 251
  drop: iron_sword@251!~&rUnfinished Iron Sword &4(Hot)
```

---

(The damage values are so that all of the parts immediately break when one tries to use them.)

And this for Cauldrons:

---

```
cauldron:
- permission: smithsforgingdrops
  trigger: left_click
  tool: iron_sword@251
  lorename: "&rUnfinished Iron Sword &4(Hot)"
  damagetool: 251
  effect: [extinguish, extinguish, extinguish, smoke@up]
  drop: iron_sword@251!~&rUnfinished Iron Sword &3(Cooled)
```

---

You see, it checks for the name "&rUnfinished Iron Sword &4(Hot)", the "(Hot)" in dark red and the whole name gets its formatting reset first (because I don't want it to be italic, which is the standard). But it doesn't work.

I've set "verbosity" to "extreme" in the config, and found out that, while it checks for the formatting, it doesn't find it on the tool I am using even though it's there. It just sees the name, without any formatting codes, but it checks against formatting codes, so the comparison fails and it doesn't work.

![unbenannt](https://f.cloud.github.com/assets/4943543/750904/934f7ef0-e4df-11e2-9b65-7b489359cf65.jpg)

Can you help me with this? Am I doing something wrong?

Oh, and I'm using craftbukkit-1.5.2-R1.0 and... uhm... version v2.8b.566 according to the server console, even if I can't recall downloading the new version for 1.6.1.
