### ISSUE TITLE
ANY_BLOCK initiating when mobs are hit with projectiles (maybe other times as well)

### ISSUE THREAD

**Issue by CultistO** [Zarius/Bukkit-OtherBlocks#287]
Otherdrops 2.8b.573 

config:

```
ANY_BLOCK:
  - trigger: PROJECTILE_HIT_BLOCK
    tool: PROJECTILE_SNOWBALL
    lorename: "&rpokeball"
    drop: SNOWBALL;~&rpokeball
```

If you have a config like this, I would expect it NOT to drop the item when the snowball hits a mob, however it does
