### ISSUE TITLE
No way to specify enchantments for PRIOJECTILE_HIT_BLOCK

### ISSUE THREAD

**Issue by CultistO** [Zarius/Bukkit-OtherBlocks#290]
I'm trying to perform the following, but neither config works

```
WOOD:
 - trigger: PROJECTILE_HIT_BLOCK
   tool: BOW@!ARROW_FIRE
   replacementblock: FIRE
```

(Does nothing)

```
WOOD:
 - trigger: PROJECTILE_HIT_BLOCK
   tool: PROJECTILE_ARROW@!ARROW_FIRE
   replacementblock: FIRE
```

(works regardless of enchantment)
