### ISSUE TITLE
A way to ensure only one drop from dropgroups

### ISSUE THREAD

**Issue by rePewtr** [Zarius/Bukkit-OtherBlocks#317]
Hey,

what i am looking for is basically what {curly brackets} do, just for whole drops within a dropgroup. As example:

```
    dropgroup: mmspawn
    chance: 100%
    drops:
      - command: /examplecommand
        chance: 40%
        delay: 100
      - command: /examplecommand2
        chance: 15%
        delay: 120
      - command: /examplecommand3
        chance: 10%
        delay: 160
```

Some way to ensure that only ONE of the commands gets executed.
