### ISSUE TITLE
Issues with Displaying money% in 2.8-beta

### ISSUE THREAD

**Issue by DarthMarkain** [Zarius/Bukkit-OtherBlocks#319]
Hay there, first of thanks for the awesome (and i do mean awesome) plugin, having a bit of an issue with it though.

using 2.8-beta

Ok, so the aim is to have players lose 5% of their money on re-spawn, and have a message telling them how much they lost.

The losing 5% of their money works, having issues displaying the amount lost. 

So, for the 5% working we have 

```
player:
    - trigger: player_respawn
      money: -5%
      message: "&eWell, that went badly... Worse yet you lost &9%q &eCog's"
```

Now, I realise that I am missing an actual quantity so %q won't work to display the amount lost. Looking though the documentation I cannot find what to replace it with. Is this doable at this time, if so what do I need to do?

If not, could it become doable? It would be greatly appreciated as it seems to be doable using the money@percentpenalty drop in older versions. (which I think would look like this:

player:
     - trigger: player_respawn
       drop: money@percentpenalty /5
      message: "insert message hear with %q"

or something very close)

Many thanks - DarthMarkain
