### ISSUE TITLE
mobs droping 2x amount of items

### ISSUE THREAD

**Issue by jsimmons10** [Zarius/Bukkit-OtherBlocks#326]
```
 wither:
   - drop: feather/1
     chance: 100%

   - drop: 10266/1
     chance: 30%
```

and yet there droping 2 of the items
