### ISSUE TITLE
[2.8b.573] Aliases: java.lang.NullPointerException using aliases making more than 1 drop

### ISSUE THREAD

**Issue by h3oCharles** [Zarius/Bukkit-OtherBlocks#332]
Using aliases with multiple files, you cant have 1 alias to be bound to more than 1 drop at same time. Otherwise you get java.lang.NullPointerException after reloading the config files and plugin is not able to run

Or maybe did I just wrote the script wrong way?

Here is an example script exploiting the bug:

```
aliases:
    - &default  # alias "default" is suposed to:
    - drop: SPONGE/1/5% # drop 1 sponge with 5% chance
      sound: LEVEL_UP # and emit LEVEL_UP sound
      message: '&6[OtherDrops] &b&lPora na szczescie!' # AND display this message
    - drop: BAT/1 # It will also drop a bat
    - drop: XP/1-30 # give 30XP
    - drop: MONEY/1-30 # give 30 Money
      message: '&6[OtherDrops] &a&l+ %q $!' # with this message telling how much money dropped
    - &bone # second alias
    - drop: BONE/1-4 # drops 1 to max 4 bones
      sound: SKELETON_HURT # with sound of SKELETON_HURT
    - drop: INK_SACK:15/1-8 # and drops 1-8 ink sac with data of 15, which is Bone Meal
      sound: SKELETON_HURT # and emits this sound

otherdrops:
    ZOMBIE: # when zombie dies
        - *default # executes default alias
        - *bone # and bone alias
```
