### ISSUE TITLE
Using dropgroups seems to spam the chat

### ISSUE THREAD

**Issue by AzXeus** [Zarius/Bukkit-OtherBlocks#339]
In Cauldron 1.7.10  ... 198 server
      OtherDrops version: 2.7.1

**Description:** Using a dropgroup seems to spam the in game chat with blank lines
                    Whereas dropping outside a dropgroup is fine.

**Config:**

```
  otherdrops:

  18:
   - default

- dropgroup: stickn
  tool: nothing
  chance: 15
  drops:

    - drop: stick

    - drop: stick
      chance: 30

    - dropgroup: stickn2
      chance: 10
      drops:
        - drop: stick
          quantity: 2

        - drop: stick
          chance: 7
          quantity: 3

- dropgroup: sticks
  message: null
  tool: stick
  chance: 25
  drops:

    - drop: stick      

    - drop: stick       
      chance: 30

    - dropgroup: sticks2
      message: null        
      chance: 10
      drops:
        - drop: stick            
          quantity: 2

        - drop: stick
          chance: 7
          quantity: 3    



- drop: sapling@this
  chance: 5
```

**Steps to reproduce the problem:**
use the config provided, hit leaves with stick, when stick drops blank line appears in chat.
