### ISSUE TITLE
Trouble creating custom drops.

### ISSUE THREAD

**Issue by Jtalia10** [Zarius/Bukkit-OtherBlocks#359]
This isn't really a plugin issue I don't think, its just my drops I put in the otherdrops-drops.yml file aren't working in game. I think maybe its because I am inputting it wrong? I need this to drop from players and I couldn't find any of your instructions that specified those actions so I kind of just guessed; I am assuming thats where I went wrong. Any help is appreciated, I am using this for a series.
Here is what I put: 

# mojo8309
# - drop: Ghast_Tear
#   chance: 100%
#   name: Soul
#
# Jtalia10
# - drop: Ghast_Tear
#   chance: 100%
#   name: Soul
#
# player
# - drop: Ghast_Tear
#   chance: 100%
#   name: Soul
#
# Jtalia10
# - drop: Ghast_Tear
#   chance: 100%
#
# Pig
# - drop: APPLE
#  chance: 100%

I have multiple for the Jtalia10 character to test if the -name catergory just didn't work. I even tried the pig one, but it didn't work either. 

I apologize in advance, I have little experience with this stuff (other than Essentials group manager), so I am probably just making a big mistake here. Thank you for cooperating with my stupidity!

**Comment by Zarius** [comment]
You're probably not having this problem still but just for anyone with the same issue the config should be as below (noting you can't use the player name directly, just player@<name>).

```
player@mojo8309:
  - drop: Ghast_Tear
    chance: 100%
    lorename: Soul

player@Jtalia10:
  - drop: Ghast_Tear
    chance: 100%
    lorename: Soul

Pig:
  - drop: APPLE
    chance: 100%
```
